version: "3"
services:
  ddns-go:
    container_name: ddns-go
    image: jeessy/ddns-go
    network_mode: bridge
    ports:
      - "9876:9876"
    restart: unless-stopped
    volumes:
      - /volume1/docker/ddns-go/ddns-go:/root
