version: "3"
services:
  qbittorrent:
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          memory: 2048M
    image: superng6/qbittorrent
    network_mode: host
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: Asia/Shanghai
      WEBUI_PORT: 8999
    volumes:
      - /volume1/docker/qbittorrent/qbittorrent:/config
      - /volume3/media:/media
