version: "3"
services:
  minio:
    container_name: minio
    image: minio/minio
    network_mode: bridge
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
    volumes:
      - /volume1/docker/minio/minio:/data
    command: server /data  --console-address ":9001"
