version: '3.5'
services:
  dst-server:
    container_name: dst-server
    image: jamesits/dst-server:latest
    restart: unless-stopped
    ports:
       - "10999-11000:10999-11000/udp"
       - "12346-12347:12346-12347/udp"
    environment:
      # HTTP_PROXY: ${HTTP_PROXY}
    network_mode: bridge
    volumes:
       - /volume1/docker/dst-server/dst-server:/data
    stop_grace_period: 6m
